name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 6.0.1
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.18.0
  template_string:
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
