name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 6.0.5
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  meta: ^1.15.0
  template_string:
    # path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
