name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 6.0.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  template_string:
    path: ../template_string
