name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 6.0.7
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  meta: any
  template_string:
    #path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
