name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 6.0.1
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.5
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.3.1
  source_gen: ^1.3.2
  flutter_sheet_localization:
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: flutter_sheet_localization
  template_string:
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  build: ^2.0.0
  analyzer: ^5.13.0
  collection: ^1.17.1
  intl: ^0.18.0
  localization_builder:
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.4.5
