name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 6.0.4
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.1.2
  meta: ^1.10.0
  csv: ^5.1.1
  recase: ^4.0.0
  code_builder: ^4.8.0
  dart_style: ^2.3.1
  source_gen: ^1.3.2
  flutter_sheet_localization:
    # path: ../flutter_sheet_localization
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: flutter_sheet_localization
  template_string:
    # path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  build: ^2.0.0
  analyzer: ^6.2.0
  collection: ^1.17.1
  intl: ^0.18.0
  localization_builder:
    # path: ../localization_builder
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.2.1
  build_runner: ^2.4.5
