name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 6.0.5
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.2.1
  meta: ^1.15.0
  csv: ^6.0.0
  recase: ^4.0.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  source_gen: ^1.5.0
  flutter_sheet_localization:
    # path: ../flutter_sheet_localization
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: flutter_sheet_localization
  template_string:
    # path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  build: ^2.0.0
  analyzer: ^6.5.0
  collection: ^1.17.1
  intl: ^0.19.0
  localization_builder:
    # path: ../localization_builder
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.2.2
  build_runner: ^2.4.10

dependency_overrides:
  meta: ^1.15.0
