name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 6.0.8
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.4.0
  meta: any
  csv: ^6.0.0
  recase: ^4.0.0
  code_builder: ^4.10.1
  dart_style: ^3.1.2
  source_gen: ^3.1.0
  flutter_sheet_localization:
    #path: ../flutter_sheet_localization
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: flutter_sheet_localization
  template_string:
    #path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  build: ^3.0.2
  analyzer: ^8.1.1
  collection: ^1.17.1
  intl: ^0.20.2
  localization_builder:
    #path: ../localization_builder
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^3.2.2
  build_runner: ^2.4.15
