name: template_string
description: A simple command-line application.
version: 0.7.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  pedantic: ^1.9.0
