name: template_string
description: A simple command-line application.
version: 0.7.1
homepage: https://github.com/mboe/flutter_sheet_localization

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  meta: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.1
