name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/mboe/flutter_sheet_localization
version: 0.16.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  template_string:
    # path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  recase: ^4.0.0
  meta: ^1.15.0
  yaml: ^3.1.0
  equatable: ^2.0.0
  collection: ^1.17.1
  dart_style: ^2.3.6
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.5

dependency_overrides:
  meta:  ^1.15.0