name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/mboe/flutter_sheet_localization
version: 0.16.2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  template_string:
    # path: ../template_string
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  recase: ^4.0.0
  meta: ^1.15.0
  yaml: ^3.1.3
  equatable: ^2.0.7
  collection: ^1.17.1
  dart_style: ^3.0.1
  logging: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.5
