name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/mboe/flutter_sheet_localization
version: 0.16.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  template_string:
    git:
      url: https://github.com/mboe/flutter_sheet_localization.git
      path: template_string
  recase: ^4.0.0
  yaml: ^3.1.0
  equatable: ^2.0.0
  collection: ^1.17.1
  dart_style: ^2.0.0
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0
